services:
  client:
    build:
      context: ./client
      args:
        VITE_CLERK_PUBLISHABLE_KEY: ${VITE_CLERK_PUBLISHABLE_KEY}
        VITE_BASE_URL: ${VITE_BASE_URL}
    ports:
      - "5173:5173"

  server:
    build:
      context: ./server
    ports:
      - "3000:3000"
    env_file:
      - ./server/.env